config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "service/",
        TemplateView.as_view(template_name="pages/service.html"),
        name="service",
    ),
    path(
        "instruments/",
        TemplateView.as_view(template_name="pages/instruments.html"),
        name="instruments",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("cyril_violins.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

cyril_violins/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

cyril_violins/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.db.models import EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Cyril Violins.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore[assignment]

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: ClassVar[UserManager] = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

cyril_violins/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

cyril_violins/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from cyril_violins.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None = None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

cyril_violins/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

cyril_violins/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Cyril Violins
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Cyril Violins" />
    <meta name="author" content="Hari" />
    <link rel="apple-touch-icon"
          sizes="57x57"
          href="{% static 'images/favicons/apple-icon-57x57.png' %}" />
    <link rel="apple-touch-icon"
          sizes="60x60"
          href="{% static 'images/favicons/apple-icon-60x60.png' %}" />
    <link rel="apple-touch-icon"
          sizes="72x72"
          href="{% static 'images/favicons/apple-icon-72x72.png' %}" />
    <link rel="apple-touch-icon"
          sizes="76x76"
          href="{% static 'images/favicons/apple-icon-76x76.png' %}" />
    <link rel="apple-touch-icon"
          sizes="114x114"
          href="{% static 'images/favicons/apple-icon-114x114.png' %}" />
    <link rel="apple-touch-icon"
          sizes="120x120"
          href="{% static 'images/favicons/apple-icon-120x120.png' %}" />
    <link rel="apple-touch-icon"
          sizes="144x144"
          href="{% static 'images/favicons/apple-icon-144x144.png' %}" />
    <link rel="apple-touch-icon"
          sizes="152x152"
          href="{% static 'images/favicons/apple-icon-152x152.png' %}" />
    <link rel="apple-touch-icon"
          sizes="180x180"
          href="{% static 'images/favicons/apple-icon-180x180.png' %}" />
    <link rel="icon"
          type="image/png"
          sizes="192x192"
          href="/android-icon-192x192.png" />
    <link rel="icon"
          type="image/png"
          sizes="32x32"
          href="{% static 'images/favicons/favicon-32x32.png' %}" />
    <link rel="icon"
          type="image/png"
          sizes="96x96"
          href="{% static 'images/favicons/favicon-96x96.png' %}" />
    <link rel="icon"
          type="image/png"
          sizes="16x16"
          href="{% static 'images/favicons/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% static 'images/favicons/manifest.json' %}" />
    <meta name="msapplication-TileColor" content="#ffffff" />
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
    <meta name="theme-color" content="#ffffff" />
    {% block css %}
      <!-- Latest compiled and minified Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous" />
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      <link href="{% static 'css/project.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" /> {% endcomment %}
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body class="{% block bodyclass %}{% endblock bodyclass %}">
    {% block body %}
      <div class="mb-1">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
          <div class="container-fluid">
            <button class="navbar-toggler navbar-toggler-right"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Cyril Violins</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
                  </li>
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                  </li>
                {% else %}
                  {% if ACCOUNT_ALLOW_REGISTRATION %}
                    <li class="nav-item">
                      {# URL provided by django-allauth/account/urls.py #}
                      <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                    </li>
                  {% endif %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="alert"
                      aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        {% block main %}
          {% block content %}
            <p>Use this document as a way to quick start any new project.</p>
          {% endblock content %}
        {% endblock main %}
      </div>
    {% endblock body %}
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>

cyril_violins/templates/pages/about.html
{% extends "base.html" %}

cyril_violins/templates/pages/instruments.html
{% extends "base.html" %}

{% block content %}
  <h1>INSTRUMENT LIST</h1>
{% endblock content %}

cyril_violins/templates/pages/service.html
{% extends "base.html" %}

{% block content %}
  <h1>SERVICE LIST</h1>
{% endblock content %}

cyril_violins/templates/users/user_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  User:
  {{ object.name }}
{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>{{ object.name }}</h2>
      </div>
    </div>
    {% if object == request.user %}
      <!-- Action buttons -->
      <div class="row">
        <div class="col-sm-12">
          <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
          <a class="btn btn-primary"
             href="{% url 'account_email' %}"
             role="button">E-Mail</a>
          <a class="btn btn-primary" href="{% url 'mfa_index' %}" role="button">MFA</a>
          <!-- Your Stuff: Custom user template urls -->
        </div>
      </div>
      <!-- End Action buttons -->
    {% endif %}
  </div>
{% endblock content %}

cyril_violins/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  {{ user.name }}
{% endblock title %}
{% block content %}
  <h1>{{ user.name }}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock content %}